### ISSUE TITLE
pugixml.hpp: No such file while building

### ISSUE THREAD

**Issue by pbertoni** [blockmon/blockmon#1]
Assume a fresh git clone of the repo, 
<pre><code>cmake . && make </code></pre> will end in a
<pre><code>In file included from /root/blockmon/core/block/Block.cpp:32:0:
/root/blockmon/core/block/Block.hpp:52:23: fatal error: pugixml.hpp: No such file or directory</code></pre>
While <pre><code>ldconfig -p | grep pugi</code></pre> produces
<pre><code>libpugixml.so.1 (libc6,x86-64) => /usr/lib/x86_64-linux-gnu/libpugixml.so.1
</code></pre>
And my system, Ubuntu 14.04.1 LTS x64, has <pre><code>libpugixml1</code></pre> installed by  <pre><code>apt-get</code></pre>
What's wrong ?

**Comment by awgn** [comment]
Don't remember if blockmon is shipped with pugi library. However, it seems that your compiler is not able to find the pugi header. Try to install libpugixml-dev  package from [universe] repo.

**Comment by pbertoni** [comment]
Thank you Nicola, but it astonishes me that next error is
<pre><code>~/blockmon/ipfix/IPFIXTypeBridge.hpp:52:28: fatal error: RecordReceiver.h: No such file or directory</code></pre>
I've googled for that header, even downloaded and built http://sourceforge.net/projects/libipfix/, but no way..

**Comment by awgn** [comment]
Patrizio, not sure what's going on there and I'm not even sure if someone
is still in charge to maintain the code (me not for sure).

What I can tell you is that from time to time Maurizio Dusi pushes some
commits... Try to send an email to him.

N.
